$base = "C:\Users\HP\Downloads\TraceIQ"
if (!(Test-Path $base)) { New-Item -ItemType Directory -Force -Path $base }

$files = @(
    "README.md",
    ".env.example",
    ".gitignore",
    "docker-compose.yml",
    "Makefile",
    "docs/ARCHITECTURE.md",
    "docs/API_CONTRACT.md",
    "docs/TEAM_WORKPLAN.md",
    "docs/FILE_OWNERSHIP.md",
    "docs/DEMO_SCRIPT.md",
    "docs/SECURITY.md",
    "docs/DEPLOYMENT.md",
    "docs/DEVELOPMENT.md",
    "docs/AI_USAGE.md",
    "docs/TROUBLESHOOTING.md",
    "backend/Dockerfile",
    "backend/requirements.txt",
    "backend/pyproject.toml",
    "backend/app/__init__.py",
    "backend/app/main.py",
    "backend/app/config.py",
    "backend/app/api/__init__.py",
    "backend/app/api/investigate.py",
    "backend/app/api/github.py",
    "backend/app/api/monitoring.py",
    "backend/app/api/voice.py",
    "backend/app/api/health.py",
    "backend/app/integrations/__init__.py",
    "backend/app/integrations/github.py",
    "backend/app/integrations/github_actions.py",
    "backend/app/integrations/monitoring.py",
    "backend/app/integrations/rime.py",
    "backend/app/rag/__init__.py",
    "backend/app/rag/qdrant_client.py",
    "backend/app/rag/ingest.py",
    "backend/app/rag/chunker.py",
    "backend/app/rag/embeddings.py",
    "backend/app/rag/retriever.py",
    "backend/app/rag/reranker.py",
    "backend/app/rag/prompts.py",
    "backend/app/services/__init__.py",
    "backend/app/services/orchestrator.py",
    "backend/app/services/llm.py",
    "backend/app/services/evidence_builder.py",
    "backend/app/services/evidence_validator.py",
    "backend/app/services/confidence.py",
    "backend/app/services/incident_timeline.py",
    "backend/app/services/recommendation.py",
    "backend/app/services/demo_mode.py",
    "backend/app/services/report_generator.py",
    "backend/app/schemas/__init__.py",
    "backend/app/schemas/common.py",
    "backend/app/schemas/engineering.py",
    "backend/app/schemas/investigation.py",
    "backend/app/schemas/evidence.py",
    "backend/app/schemas/voice.py",
    "backend/app/middleware/__init__.py",
    "backend/app/middleware/error_handler.py",
    "backend/app/middleware/logging.py",
    "backend/app/middleware/security.py",
    "backend/app/middleware/rate_limit.py",
    "backend/app/utils/__init__.py",
    "backend/app/utils/sanitization.py",
    "backend/app/utils/timestamps.py",
    "backend/app/utils/secrets.py",
    "backend/tests/__init__.py",
    "backend/tests/test_github.py",
    "backend/tests/test_github_actions.py",
    "backend/tests/test_monitoring.py",
    "backend/tests/test_qdrant.py",
    "backend/tests/test_embeddings.py",
    "backend/tests/test_retrieval.py",
    "backend/tests/test_investigation.py",
    "backend/tests/test_evidence.py",
    "backend/tests/test_api.py",
    "backend/tests/test_voice.py",
    "frontend/package.json",
    "frontend/vite.config.js",
    "frontend/index.html",
    "frontend/Dockerfile",
    "frontend/src/main.jsx",
    "frontend/src/App.jsx",
    "frontend/src/pages/Connect.jsx",
    "frontend/src/pages/Dashboard.jsx",
    "frontend/src/pages/Incident.jsx",
    "frontend/src/pages/NotFound.jsx",
    "frontend/src/components/layout/Navbar.jsx",
    "frontend/src/components/layout/Sidebar.jsx",
    "frontend/src/components/layout/PageContainer.jsx",
    "frontend/src/components/incident/IncidentHeader.jsx",
    "frontend/src/components/incident/IncidentTimeline.jsx",
    "frontend/src/components/incident/EvidencePanel.jsx",
    "frontend/src/components/incident/SimilarIncidents.jsx",
    "frontend/src/components/incident/ConfidenceScore.jsx",
    "frontend/src/components/incident/RecommendationCard.jsx",
    "frontend/src/components/voice/VoiceConsole.jsx",
    "frontend/src/components/voice/MicrophoneButton.jsx",
    "frontend/src/components/voice/Waveform.jsx",
    "frontend/src/components/voice/Transcript.jsx",
    "frontend/src/components/common/Loading.jsx",
    "frontend/src/components/common/ErrorState.jsx",
    "frontend/src/components/common/StatusBadge.jsx",
    "frontend/src/components/common/EvidenceBadge.jsx",
    "frontend/src/lib/api.js",
    "frontend/src/lib/voice.js",
    "frontend/src/lib/github.js",
    "frontend/src/hooks/useInvestigation.js",
    "frontend/src/hooks/useVoice.js",
    "frontend/src/hooks/useRepository.js",
    "frontend/src/types/investigation.js",
    "frontend/src/types/github.js",
    "frontend/src/types/evidence.js",
    "frontend/src/types/voice.js",
    "frontend/src/styles/globals.css",
    "frontend/src/styles/animations.css",
    "frontend/src/styles/dashboard.css",
    "frontend/src/assets/logo.svg",
    "knowledge/README.md",
    "knowledge/incidents/INC-001.md",
    "knowledge/incidents/INC-002.md",
    "demo/README.md",
    "demo/scenario.json",
    "demo/github_context.json",
    "demo/monitoring_context.json",
    "demo/historical_incidents.json",
    "deployment/README.md",
    "deployment/docker/backend.Dockerfile",
    "deployment/docker/frontend.Dockerfile",
    "deployment/nginx/nginx.conf",
    "deployment/health/README.md"
)

$dirs = @(
    "frontend/src/assets/icons",
    "knowledge/postmortems",
    "knowledge/runbooks",
    "knowledge/architecture",
    "knowledge/troubleshooting"
)

foreach ($d in $dirs) {
    $dirPath = Join-Path $base $d
    if (!(Test-Path $dirPath)) {
        New-Item -ItemType Directory -Force -Path $dirPath | Out-Null
    }
}

foreach ($f in $files) {
    $path = Join-Path $base $f
    $dir = Split-Path $path
    if (!(Test-Path $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }
    if (!(Test-Path $path)) {
        New-Item -ItemType File -Force -Path $path | Out-Null
    }
}

Write-Host "Architecture created successfully."
