"""
TraceIQ - Evidence Validator

Validates LLM-generated investigation findings against the evidence actually
collected by TraceIQ.

This is a critical anti-hallucination boundary.

The validator ensures that:
- Referenced evidence IDs actually exist.
- Causes are supported by evidence.
- Recommendations do not reference fabricated evidence.
- Confidence values are normalized.
- Invalid LLM structures are safely discarded.
- The original evidence collection is never modified.
- The validator never invents supporting evidence.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Mapping, Sequence

import structlog

from app.schemas.evidence import Evidence


logger = structlog.get_logger(__name__)


class EvidenceValidator:
    """
    Validate structured LLM output against supplied TraceIQ evidence.

    The validator is intentionally deterministic and does not call any
    external service or LLM.
    """

    def validate(
        self,
        llm_response: Mapping[str, Any] | None,
        provided_evidence: Sequence[Evidence],
    ) -> dict[str, Any]:
        """
        Validate an LLM investigation response.

        Args:
            llm_response:
                Raw structured response generated by the LLM.

            provided_evidence:
                Evidence actually collected by TraceIQ.

        Returns:
            Sanitized and evidence-grounded response.
        """

        if not isinstance(llm_response, Mapping):
            logger.warning(
                "llm_response_invalid_type",
                response_type=(
                    type(llm_response).__name__
                    if llm_response is not None
                    else "None"
                ),
            )

            return self._unsupported_response()

        valid_ids = {
            evidence.id
            for evidence in provided_evidence
            if isinstance(evidence, Evidence)
        }

        evidence_by_id = {
            evidence.id: evidence
            for evidence in provided_evidence
            if isinstance(evidence, Evidence)
        }

        response = deepcopy(
            dict(llm_response),
        )

        validated_causes = self._validate_causes(
            response.get("likely_causes"),
            valid_ids,
            evidence_by_id,
        )

        validated_recommendations = self._validate_recommendations(
            response.get("recommendations"),
            valid_ids,
        )

        follow_up_questions = self._validate_questions(
            response.get("follow_up_questions"),
        )

        summary = self._sanitize_summary(
            response.get("summary"),
        )

        response["summary"] = summary
        response["likely_causes"] = validated_causes
        response["recommendations"] = validated_recommendations
        response["follow_up_questions"] = follow_up_questions

        # --------------------------------------------------------------------
        # Determine whether the response contains enough grounded findings.
        # --------------------------------------------------------------------

        has_supported_causes = bool(
            validated_causes
        )

        has_supported_recommendations = bool(
            validated_recommendations
        )

        if not has_supported_causes:
            logger.warning(
                "no_supported_causes_after_validation",
                provided_evidence_count=len(valid_ids),
            )

        if (
            not has_supported_causes
            and not has_supported_recommendations
        ):
            logger.warning(
                "llm_response_invalidated",
                provided_evidence_count=len(valid_ids),
            )

            response["summary"] = (
                "Insufficient evidence to determine a reliable root cause."
            )

            response["likely_causes"] = []
            response["recommendations"] = []

        # --------------------------------------------------------------------
        # Attach validator metadata for downstream confidence calculation.
        # --------------------------------------------------------------------

        response["_validation"] = {
            "validated": True,
            "provided_evidence_count": len(valid_ids),
            "supported_cause_count": len(validated_causes),
            "supported_recommendation_count": len(
                validated_recommendations
            ),
            "grounded": (
                has_supported_causes
                or has_supported_recommendations
            ),
        }

        logger.info(
            "llm_response_validated",
            provided_evidence_count=len(valid_ids),
            supported_causes=len(validated_causes),
            supported_recommendations=len(
                validated_recommendations
            ),
            grounded=(
                has_supported_causes
                or has_supported_recommendations
            ),
        )

        return response

    # ========================================================================
    # LIKELY CAUSES
    # ========================================================================

    def _validate_causes(
        self,
        causes: Any,
        valid_ids: set[str],
        evidence_by_id: dict[str, Evidence],
    ) -> list[dict[str, Any]]:
        """
        Validate likely-cause objects.

        A cause is accepted only when:
        - It is a dictionary.
        - It contains a meaningful cause.
        - It contains a meaningful explanation.
        - It references at least one valid evidence ID.
        - Every referenced evidence ID actually exists.
        """

        if not isinstance(causes, list):
            return []

        validated: list[dict[str, Any]] = []

        for index, cause in enumerate(causes):
            if not isinstance(cause, Mapping):
                logger.warning(
                    "invalid_cause_structure",
                    index=index,
                )
                continue

            cause_text = self._clean_text(
                cause.get("cause"),
            )

            explanation = self._clean_text(
                cause.get("explanation"),
            )

            evidence_ids = self._normalize_evidence_ids(
                cause.get("supporting_evidence_ids"),
            )

            if not cause_text:
                logger.warning(
                    "cause_missing_description",
                    index=index,
                )
                continue

            if not explanation:
                logger.warning(
                    "cause_missing_explanation",
                    cause=cause_text,
                )
                continue

            if not evidence_ids:
                logger.warning(
                    "cause_missing_evidence_ids",
                    cause=cause_text,
                )
                continue

            invalid_ids = [
                evidence_id
                for evidence_id in evidence_ids
                if evidence_id not in valid_ids
            ]

            if invalid_ids:
                logger.warning(
                    "hallucinated_evidence_id_in_cause",
                    cause=cause_text,
                    invalid_ids=invalid_ids,
                )
                continue

            # Make sure the evidence actually contains useful information.
            usable_ids = [
                evidence_id
                for evidence_id in evidence_ids
                if evidence_by_id[evidence_id].content.strip()
                or evidence_by_id[evidence_id].title.strip()
            ]

            if not usable_ids:
                logger.warning(
                    "cause_references_empty_evidence",
                    cause=cause_text,
                )
                continue

            confidence = self._normalize_confidence(
                cause.get("confidence"),
            )

            validated.append(
                {
                    "cause": cause_text,
                    "explanation": explanation,
                    "supporting_evidence_ids": usable_ids,
                    "confidence": confidence,
                }
            )

        return validated

    # ========================================================================
    # RECOMMENDATIONS
    # ========================================================================

    def _validate_recommendations(
        self,
        recommendations: Any,
        valid_ids: set[str],
    ) -> list[dict[str, Any]]:
        """
        Validate recommendation objects.

        Recommendations may be retained without evidence IDs only when they
        are clearly phrased as verification/follow-up actions. However,
        destructive or operational actions must have supporting evidence.
        """

        if not isinstance(recommendations, list):
            return []

        validated: list[dict[str, Any]] = []

        for index, recommendation in enumerate(
            recommendations,
        ):
            if not isinstance(
                recommendation,
                Mapping,
            ):
                logger.warning(
                    "invalid_recommendation_structure",
                    index=index,
                )
                continue

            action = self._clean_text(
                recommendation.get("action"),
            )

            reason = self._clean_text(
                recommendation.get("reason"),
            )

            evidence_ids = self._normalize_evidence_ids(
                recommendation.get(
                    "supporting_evidence_ids"
                ),
            )

            if not action:
                logger.warning(
                    "recommendation_missing_action",
                    index=index,
                )
                continue

            if not reason:
                logger.warning(
                    "recommendation_missing_reason",
                    action=action,
                )
                continue

            invalid_ids = [
                evidence_id
                for evidence_id in evidence_ids
                if evidence_id not in valid_ids
            ]

            if invalid_ids:
                logger.warning(
                    "hallucinated_evidence_id_in_recommendation",
                    action=action,
                    invalid_ids=invalid_ids,
                )
                continue

            # Recommendations without evidence are not reliable enough to
            # present as evidence-backed operational guidance.
            if not evidence_ids:
                logger.warning(
                    "recommendation_missing_evidence_ids",
                    action=action,
                )
                continue

            priority = self._normalize_priority(
                recommendation.get("priority"),
            )

            validated.append(
                {
                    "action": action,
                    "reason": reason,
                    "priority": priority,
                    "supporting_evidence_ids": evidence_ids,
                }
            )

        return validated

    # ========================================================================
    # FOLLOW-UP QUESTIONS
    # ========================================================================

    @staticmethod
    def _validate_questions(
        questions: Any,
    ) -> list[str]:
        """
        Validate follow-up questions.

        Questions are informational and do not require evidence IDs.
        """

        if not isinstance(questions, list):
            return []

        validated: list[str] = []

        seen: set[str] = set()

        for question in questions:
            cleaned = (
                str(question).strip()
                if question is not None
                else ""
            )

            if not cleaned:
                continue

            if len(cleaned) > 500:
                cleaned = cleaned[:500].rstrip() + "..."

            normalized = cleaned.lower()

            if normalized in seen:
                continue

            seen.add(normalized)
            validated.append(cleaned)

            if len(validated) >= 10:
                break

        return validated

    # ========================================================================
    # FIELD NORMALIZATION
    # ========================================================================

    @staticmethod
    def _normalize_evidence_ids(
        evidence_ids: Any,
    ) -> list[str]:
        """
        Normalize evidence IDs.

        Duplicates are removed while preserving the original order.
        """

        if not isinstance(evidence_ids, list):
            return []

        normalized: list[str] = []
        seen: set[str] = set()

        for evidence_id in evidence_ids:
            if evidence_id is None:
                continue

            value = str(evidence_id).strip()

            if not value:
                continue

            if value in seen:
                continue

            seen.add(value)
            normalized.append(value)

        return normalized

    @staticmethod
    def _normalize_confidence(
        confidence: Any,
    ) -> str:
        """
        Normalize confidence to the TraceIQ schema values.
        """

        if confidence is None:
            return "low"

        value = str(
            confidence,
        ).strip().lower()

        if value in {
            "high",
            "medium",
            "low",
        }:
            return value

        # Support common model outputs.
        if value in {
            "very high",
            "certain",
            "strong",
        }:
            return "high"

        if value in {
            "moderate",
            "medium-high",
            "medium high",
        }:
            return "medium"

        return "low"

    @staticmethod
    def _normalize_priority(
        priority: Any,
    ) -> str:
        """
        Normalize recommendation priority to the TraceIQ Severity enum.
        """

        if priority is None:
            return "medium"

        value = str(
            priority,
        ).strip().lower()

        if value in {
            "critical",
            "high",
            "medium",
            "low",
        }:
            return value

        if value in {
            "urgent",
            "immediate",
            "p0",
        }:
            return "critical"

        if value in {
            "p1",
            "important",
        }:
            return "high"

        if value in {
            "p2",
            "normal",
        }:
            return "medium"

        if value in {
            "p3",
            "minor",
        }:
            return "low"

        return "medium"

    @staticmethod
    def _clean_text(
        value: Any,
    ) -> str:
        """
        Convert a model-generated value to safe bounded text.
        """

        if value is None:
            return ""

        text = str(value).strip()

        if len(text) > 8_000:
            text = text[:8_000].rstrip() + "..."

        return text

    @staticmethod
    def _sanitize_summary(
        summary: Any,
    ) -> str:
        """
        Sanitize the top-level summary.
        """

        text = EvidenceValidator._clean_text(
            summary,
        )

        if not text:
            return (
                "No investigation summary was generated."
            )

        return text

    # ========================================================================
    # FALLBACK
    # ========================================================================

    @staticmethod
    def _unsupported_response() -> dict[str, Any]:
        """
        Return a safe response when the LLM output cannot be interpreted.
        """

        return {
            "summary": (
                "Insufficient evidence to determine a reliable root cause."
            ),
            "likely_causes": [],
            "recommendations": [],
            "follow_up_questions": [],
            "_validation": {
                "validated": False,
                "provided_evidence_count": 0,
                "supported_cause_count": 0,
                "supported_recommendation_count": 0,
                "grounded": False,
            },
        }


__all__ = [
    "EvidenceValidator",
]