"""
TraceIQ - Voice Schemas

Pydantic contracts for TraceIQ voice interactions.

The voice layer is intentionally separated from the investigation engine:

    Voice Input
        ↓
    Speech Processing
        ↓
    Investigation Request
        ↓
    Investigation Engine
        ↓
    Investigation Response
        ↓
    Voice Response

Voice functionality is optional. TraceIQ's core investigation workflow
must never depend on the voice provider being available.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import Field

from app.schemas.common import (
    BaseTraceIQModel,
    ConfidenceLevel,
)


# ============================================================================
# ENUMS
# ============================================================================


class VoiceInputType(str, Enum):
    """Type of voice input received by the system."""

    AUDIO = "audio"
    TEXT = "text"


class VoiceOutputFormat(str, Enum):
    """Supported synthesized voice output formats."""

    MP3 = "mp3"
    WAV = "wav"
    PCM = "pcm"


class VoiceProcessingStatus(str, Enum):
    """Lifecycle status of a voice processing request."""

    RECEIVED = "received"
    TRANSCRIBING = "transcribing"
    PROCESSING = "processing"
    SYNTHESIZING = "synthesizing"
    COMPLETED = "completed"
    FAILED = "failed"


# ============================================================================
# VOICE REQUEST
# ============================================================================


class VoiceRequest(BaseTraceIQModel):
    """
    Request for a voice-based TraceIQ interaction.

    The request may contain either already-transcribed text or a reference
    to uploaded audio. Actual file handling belongs to the API/integration
    layer, not this schema.
    """

    input_type: VoiceInputType = Field(
        default=VoiceInputType.TEXT,
        description="Type of input supplied by the client.",
    )

    transcript: str | None = Field(
        default=None,
        max_length=20000,
        description="Already-transcribed user speech.",
    )

    language: str | None = Field(
        default="en-IN",
        max_length=20,
        description="BCP-47 language code.",
    )

    conversation_id: str | None = Field(
        default=None,
        max_length=500,
        description="Conversation identifier for continuity.",
    )

    incident_id: str | None = Field(
        default=None,
        max_length=500,
        description="Known incident identifier.",
    )

    service: str | None = Field(
        default=None,
        max_length=500,
        description="Service associated with the voice request.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional client metadata.",
    )


# ============================================================================
# TRANSCRIPTION
# ============================================================================


class TranscriptionResult(BaseTraceIQModel):
    """Result produced by the speech-to-text stage."""

    transcript: str = Field(
        min_length=1,
        max_length=50000,
        description="Transcribed text.",
    )

    language: str = Field(
        min_length=2,
        max_length=20,
        description="Detected or requested language.",
    )

    confidence: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Speech recognition confidence.",
    )

    duration_seconds: float | None = Field(
        default=None,
        ge=0.0,
        description="Duration of the source audio.",
    )


# ============================================================================
# VOICE RESPONSE
# ============================================================================


class VoiceResponse(BaseTraceIQModel):
    """
    Response returned by a voice interaction.

    `text` remains the authoritative response. Audio is optional so that
    clients can gracefully fall back to text when voice synthesis is
    unavailable.
    """

    request_id: str = Field(
        min_length=1,
        max_length=500,
        description="Unique voice request identifier.",
    )

    status: VoiceProcessingStatus = Field(
        description="Current voice processing status.",
    )

    text: str = Field(
        min_length=1,
        max_length=50000,
        description="Text response generated by TraceIQ.",
    )

    audio_url: str | None = Field(
        default=None,
        description="Optional URL/reference to synthesized audio.",
    )

    audio_format: VoiceOutputFormat | None = Field(
        default=None,
        description="Format of generated audio.",
    )

    transcript: str | None = Field(
        default=None,
        description="User speech transcript.",
    )

    investigation_id: str | None = Field(
        default=None,
        description="Associated TraceIQ investigation ID.",
    )

    confidence: ConfidenceLevel | None = Field(
        default=None,
        description="Confidence of the underlying investigation response.",
    )

    processing_time_ms: float | None = Field(
        default=None,
        ge=0.0,
        description="Total processing duration.",
    )


# ============================================================================
# VOICE STATUS
# ============================================================================


class VoiceStatusResponse(BaseTraceIQModel):
    """Lightweight status response for voice processing."""

    request_id: str = Field(
        min_length=1,
        max_length=500,
    )

    status: VoiceProcessingStatus = Field(
        description="Current processing status.",
    )

    message: str | None = Field(
        default=None,
        max_length=5000,
    )

    progress: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Normalized processing progress.",
    )


# ============================================================================
# EXPORTS
# ============================================================================


__all__ = [
    "VoiceInputType",
    "VoiceOutputFormat",
    "VoiceProcessingStatus",
    "VoiceRequest",
    "TranscriptionResult",
    "VoiceResponse",
    "VoiceStatusResponse",
]